site_name: Shimon Darshan
site_url: https://ShimonDarshan.github.io




theme:
  name: material
  language: en
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
  - navigation.tabs
nav:
  - Home: index.md
  - DevOps: devops/what-is-devops.md
  - Python: blog/what-is-python.md
  - Tags: tags.md 
  - About: about.md

plugins: 
  - tags:
      enabled: true
      tags_file: tags.md
  - blog:
      blog_dir: .
      categories: true
      archive: false
  - search


extra:
  analytics:
    provider: google
    property: !ENV GANALYTICSTOKEN