site_name: My Blog
site_url: https://ShimonDarshan.github.io
repo_url: https://github.com/ShimonDarshan/ShimonDarshan.github.io
remote_name: https://github.com/ShimonDarshan/ShimonDarshan.github.io
remote_branch: gh-pages

theme:
  name: material
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search:
      lang: en
  - tags

copyright: |
  &copy; 2025 Shimon Darshan.<br/>

extra:
  generator: false
  analytics:
    provider: google
    property: G-LNCCESZGPP
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/shimond/
      name: LinkedIn




nav:
  - index.md
  - Blog:
      - index: blog/index.md
